
services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
      - RUN_MODE=server
    command: uvicorn index:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env 